### ISSUE TITLE
Long Term To-Do List

### ISSUE THREAD

**Issue by steviegt6** [steviegt6/terraprisma#10]
The Terraprisma Project has several long-term goals, varying in importance:
- [x] create a unified Terraria build which may be safely distributed without promoting privacy,
  - [ ] resolve windowing issues with said build,
- [ ] set up mod loading framework and Terraprisma,
- [ ] set up bootstrapper and installer, global Terraprisma installs(?),
- unrelated, minor projects for fun:
  - [ ] open-source rewrites of libs such as `ReLogic`,
  - [ ] personal performance and optimization fork.

Other ways to help:
- once released, just stress-test Terraprisma with various mods (the more you make, the merrier!), and test on various different platforms.
- starring, spreading the project, donating, etc.
